name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create custom_components structure for hassfest
        run: |
          mkdir -p custom_components
          ln -s ${{ github.workspace }} custom_components/water_softener
      - uses: home-assistant/actions/hassfest@master
